# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

#version: 2
#updates:
#  - package-ecosystem: "" # See documentation for possible values
#    directory: "/" # Location of package manifests
#    schedule:
#      interval: "weekly"

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"

  - package-ecosystem: nuget
    directory: /DemoInstall/projects/SetSecurity
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /DemoInstall/projects/UpdateManifest
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /NasaStsTvScheduleReader
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /NasaTvSchedule
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /TimeZoneInfo
    schedule:
      interval: daily
