//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermanentVacations.Nasa.Sts.Schedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PermanentVacations.Nasa.Sts.Schedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get_Range.
        /// </summary>
        internal static string COM_EXCEPTION_INTEROPEXCEL_OPENEXCELFILE_GETRANGE {
            get {
                return ResourceManager.GetString("COM_EXCEPTION_INTEROPEXCEL_OPENEXCELFILE_GETRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeExcel.
        /// </summary>
        internal static string ERR_ARGUMENT_TYPE_EXCEL {
            get {
                return ResourceManager.GetString("ERR_ARGUMENT_TYPE_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NasaStsTVSchedule::ExcelFormatTime().
        /// </summary>
        internal static string ERR_EXCEL_FORMAT_TIME {
            get {
                return ResourceManager.GetString("ERR_EXCEL_FORMAT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteropExcelInterface::OpenExcelFile().
        /// </summary>
        internal static string ERR_INTEROP_EXCEL_OPEN_FILE {
            get {
                return ResourceManager.GetString("ERR_INTEROP_EXCEL_OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Argument.
        /// </summary>
        internal static string ERR_INVALID_ARGUMENT {
            get {
                return ResourceManager.GetString("ERR_INVALID_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NasaStsTVSchedule::ProcessOrbitHeader() Invalid Column Heading in Nasa Sts TV Schedule, row=.
        /// </summary>
        internal static string ERR_INVALID_COLUMN_HEADER {
            get {
                return ResourceManager.GetString("ERR_INVALID_COLUMN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Office.Tools.Excel Interface is not supported yet..
        /// </summary>
        internal static string ERR_MICROSOFT_OFFICE_TOOLS_EXCEL_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_MICROSOFT_OFFICE_TOOLS_EXCEL_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NasaStsTVSchedule::OpenNasaTvSchedule().
        /// </summary>
        internal static string ERR_OPEN_NASA_TV_SCHEDULE {
            get {
                return ResourceManager.GetString("ERR_OPEN_NASA_TV_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NasaStsTVSchedule::ToolsExcelOpenFile().
        /// </summary>
        internal static string ERR_TOOLS_EXCEL_OPEN_FILE {
            get {
                return ResourceManager.GetString("ERR_TOOLS_EXCEL_OPEN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Format.
        /// </summary>
        internal static string EXP_INVALID_FILE_FORMAT {
            get {
                return ResourceManager.GetString("EXP_INVALID_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermanentVacations.Nasa.Sts.Schedule.NasaStsTVSchedule.
        /// </summary>
        internal static string EXP_SOURCE {
            get {
                return ResourceManager.GetString("EXP_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation or Revision Date was not found in file {0}.  Year of the mission cannot be determined..
        /// </summary>
        internal static string INVALIDFILE_NO_REVISION_DATE {
            get {
                return ResourceManager.GetString("INVALIDFILE_NO_REVISION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range, Print_Area, is not defined in the NASA STS TV Schedule File.
        /// </summary>
        internal static string INVALIDFILEFORMAT_NO_PRINT_AREA {
            get {
                return ResourceManager.GetString("INVALIDFILEFORMAT_NO_PRINT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string IX_ACTIVITY {
            get {
                return ResourceManager.GetString("IX_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string IX_DAY {
            get {
                return ResourceManager.GetString("IX_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfWeek.
        /// </summary>
        internal static string IX_DAY_OF_WEEK {
            get {
                return ResourceManager.GetString("IX_DAY_OF_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eva.
        /// </summary>
        internal static string IX_EVA {
            get {
                return ResourceManager.GetString("IX_EVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightDay.
        /// </summary>
        internal static string IX_FLIGHT_DAY {
            get {
                return ResourceManager.GetString("IX_FLIGHT_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        internal static string IX_HIGHLIGHTS {
            get {
                return ResourceManager.GetString("IX_HIGHLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISS.
        /// </summary>
        internal static string IX_ISS {
            get {
                return ResourceManager.GetString("IX_ISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string IX_MONTH {
            get {
                return ResourceManager.GetString("IX_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle.
        /// </summary>
        internal static string IX_SHUTTLE {
            get {
                return ResourceManager.GetString("IX_SHUTTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string IX_YEAR {
            get {
                return ResourceManager.GetString("IX_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/G.
        /// </summary>
        internal static string NASA_AG {
            get {
                return ResourceManager.GetString("NASA_AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMC.
        /// </summary>
        internal static string NASA_AMC {
            get {
                return ResourceManager.GetString("NASA_AMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI.
        /// </summary>
        internal static string NASA_ASI {
            get {
                return ResourceManager.GetString("NASA_ASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGINS.
        /// </summary>
        internal static string NASA_BEGINS {
            get {
                return ResourceManager.GetString("NASA_BEGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSP.
        /// </summary>
        internal static string NASA_BSP {
            get {
                return ResourceManager.GetString("NASA_BSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPOUT.
        /// </summary>
        internal static string NASA_CAMPOUT {
            get {
                return ResourceManager.GetString("NASA_CAMPOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDT.
        /// </summary>
        internal static string NASA_CDT {
            get {
                return ResourceManager.GetString("NASA_CDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string NASA_CHANGED {
            get {
                return ResourceManager.GetString("NASA_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMG.
        /// </summary>
        internal static string NASA_CMG {
            get {
                return ResourceManager.GetString("NASA_CMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREW SLEEP BEGINS.
        /// </summary>
        internal static string NASA_CREW_SLEEP_BEGINS {
            get {
                return ResourceManager.GetString("NASA_CREW_SLEEP_BEGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREW WAKE UP.
        /// </summary>
        internal static string NASA_CREW_WAKE_UP {
            get {
                return ResourceManager.GetString("NASA_CREW_WAKE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSA.
        /// </summary>
        internal static string NASA_CSA {
            get {
                return ResourceManager.GetString("NASA_CSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CST.
        /// </summary>
        internal static string NASA_CST {
            get {
                return ResourceManager.GetString("NASA_CST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINITION OF TERMS.
        /// </summary>
        internal static string NASA_DEFINITION_OF_TERMS {
            get {
                return ResourceManager.GetString("NASA_DEFINITION_OF_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destiny.
        /// </summary>
        internal static string NASA_DESTINY {
            get {
                return ResourceManager.GetString("NASA_DESTINY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DOCKING.
        /// </summary>
        internal static string NASA_DOCKING {
            get {
                return ResourceManager.GetString("NASA_DOCKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIDAY.
        /// </summary>
        internal static string NASA_DOW_FRIDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONDAY.
        /// </summary>
        internal static string NASA_DOW_MONDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATURDAY.
        /// </summary>
        internal static string NASA_DOW_SATURDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUNDAY.
        /// </summary>
        internal static string NASA_DOW_SUNDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THURSDAY.
        /// </summary>
        internal static string NASA_DOW_THURSDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUESDAY.
        /// </summary>
        internal static string NASA_DOW_TUESDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEDNESDAY.
        /// </summary>
        internal static string NASA_DOW_WEDNESDAY {
            get {
                return ResourceManager.GetString("NASA_DOW_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTO.
        /// </summary>
        internal static string NASA_DTO {
            get {
                return ResourceManager.GetString("NASA_DTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDT.
        /// </summary>
        internal static string NASA_EDT {
            get {
                return ResourceManager.GetString("NASA_EDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU.
        /// </summary>
        internal static string NASA_EMU {
            get {
                return ResourceManager.GetString("NASA_EMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDS.
        /// </summary>
        internal static string NASA_ENDS {
            get {
                return ResourceManager.GetString("NASA_ENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESA.
        /// </summary>
        internal static string NASA_ESA {
            get {
                return ResourceManager.GetString("NASA_ESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP-2.
        /// </summary>
        internal static string NASA_ESP_2 {
            get {
                return ResourceManager.GetString("NASA_ESP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST.
        /// </summary>
        internal static string NASA_EST {
            get {
                return ResourceManager.GetString("NASA_EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        internal static string NASA_ET {
            get {
                return ResourceManager.GetString("NASA_ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETCS.
        /// </summary>
        internal static string NASA_ETCS {
            get {
                return ResourceManager.GetString("NASA_ETCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVA.
        /// </summary>
        internal static string NASA_EVA {
            get {
                return ResourceManager.GetString("NASA_EVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCS.
        /// </summary>
        internal static string NASA_FCS {
            get {
                return ResourceManager.GetString("NASA_FCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FD.
        /// </summary>
        internal static string NASA_FD {
            get {
                return ResourceManager.GetString("NASA_FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMT.
        /// </summary>
        internal static string NASA_GMT {
            get {
                return ResourceManager.GetString("NASA_GMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmony.
        /// </summary>
        internal static string NASA_HARMONY {
            get {
                return ResourceManager.GetString("NASA_HARMONY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        internal static string NASA_HQ {
            get {
                return ResourceManager.GetString("NASA_HQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISS.
        /// </summary>
        internal static string NASA_ISS {
            get {
                return ResourceManager.GetString("NASA_ISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSC.
        /// </summary>
        internal static string NASA_JSC {
            get {
                return ResourceManager.GetString("NASA_JSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KSC.
        /// </summary>
        internal static string NASA_KSC {
            get {
                return ResourceManager.GetString("NASA_KSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-.
        /// </summary>
        internal static string NASA_L_MINUS {
            get {
                return ResourceManager.GetString("NASA_L_MINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDING.
        /// </summary>
        internal static string NASA_LANDING {
            get {
                return ResourceManager.GetString("NASA_LANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH.
        /// </summary>
        internal static string NASA_LAUNCH {
            get {
                return ResourceManager.GetString("NASA_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBS.
        /// </summary>
        internal static string NASA_MBS {
            get {
                return ResourceManager.GetString("NASA_MBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBSU.
        /// </summary>
        internal static string NASA_MBSU {
            get {
                return ResourceManager.GetString("NASA_MBSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MECO.
        /// </summary>
        internal static string NASA_MECO {
            get {
                return ResourceManager.GetString("NASA_MECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET.
        /// </summary>
        internal static string NASA_MET {
            get {
                return ResourceManager.GetString("NASA_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILA.
        /// </summary>
        internal static string NASA_MILA {
            get {
                return ResourceManager.GetString("NASA_MILA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSE.
        /// </summary>
        internal static string NASA_MISSE {
            get {
                return ResourceManager.GetString("NASA_MISSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yy.
        /// </summary>
        internal static string NASA_MM_DD_YY {
            get {
                return ResourceManager.GetString("NASA_MM_DD_YY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMT.
        /// </summary>
        internal static string NASA_MMT {
            get {
                return ResourceManager.GetString("NASA_MMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL.
        /// </summary>
        internal static string NASA_MON_APRIL {
            get {
                return ResourceManager.GetString("NASA_MON_APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGUST.
        /// </summary>
        internal static string NASA_MON_AUGUST {
            get {
                return ResourceManager.GetString("NASA_MON_AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECEMBER.
        /// </summary>
        internal static string NASA_MON_DECEMBER {
            get {
                return ResourceManager.GetString("NASA_MON_DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUARY.
        /// </summary>
        internal static string NASA_MON_FEBRUARY {
            get {
                return ResourceManager.GetString("NASA_MON_FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUARY.
        /// </summary>
        internal static string NASA_MON_JANUARY {
            get {
                return ResourceManager.GetString("NASA_MON_JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JULY.
        /// </summary>
        internal static string NASA_MON_JULY {
            get {
                return ResourceManager.GetString("NASA_MON_JULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNE.
        /// </summary>
        internal static string NASA_MON_JUNE {
            get {
                return ResourceManager.GetString("NASA_MON_JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCH.
        /// </summary>
        internal static string NASA_MON_MARCH {
            get {
                return ResourceManager.GetString("NASA_MON_MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAY.
        /// </summary>
        internal static string NASA_MON_MAY {
            get {
                return ResourceManager.GetString("NASA_MON_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER.
        /// </summary>
        internal static string NASA_MON_NOVEMBER {
            get {
                return ResourceManager.GetString("NASA_MON_NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTOBER.
        /// </summary>
        internal static string NASA_MON_OCTOBER {
            get {
                return ResourceManager.GetString("NASA_MON_OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER.
        /// </summary>
        internal static string NASA_MON_SEPTEMBER {
            get {
                return ResourceManager.GetString("NASA_MON_SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSCOW.
        /// </summary>
        internal static string NASA_MOSCOW {
            get {
                return ResourceManager.GetString("NASA_MOSCOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPLM.
        /// </summary>
        internal static string NASA_MPLM {
            get {
                return ResourceManager.GetString("NASA_MPLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string NASA_MS {
            get {
                return ResourceManager.GetString("NASA_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string NASA_MT {
            get {
                return ResourceManager.GetString("NASA_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NET.
        /// </summary>
        internal static string NASA_NET {
            get {
                return ResourceManager.GetString("NASA_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETL + .
        /// </summary>
        internal static string NASA_NET_LANDING_PLUS {
            get {
                return ResourceManager.GetString("NASA_NET_LANDING_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS.
        /// </summary>
        internal static string NASA_OBS {
            get {
                return ResourceManager.GetString("NASA_OBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBSS.
        /// </summary>
        internal static string NASA_OBSS {
            get {
                return ResourceManager.GetString("NASA_OBSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMS.
        /// </summary>
        internal static string NASA_OMS {
            get {
                return ResourceManager.GetString("NASA_OMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORBIT.
        /// </summary>
        internal static string NASA_ORBIT {
            get {
                return ResourceManager.GetString("NASA_ORBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        internal static string NASA_P1 {
            get {
                return ResourceManager.GetString("NASA_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2.
        /// </summary>
        internal static string NASA_P2 {
            get {
                return ResourceManager.GetString("NASA_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3.
        /// </summary>
        internal static string NASA_P3 {
            get {
                return ResourceManager.GetString("NASA_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4.
        /// </summary>
        internal static string NASA_P4 {
            get {
                return ResourceManager.GetString("NASA_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P5.
        /// </summary>
        internal static string NASA_P5 {
            get {
                return ResourceManager.GetString("NASA_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6.
        /// </summary>
        internal static string NASA_P6 {
            get {
                return ResourceManager.GetString("NASA_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAO.
        /// </summary>
        internal static string NASA_PAO {
            get {
                return ResourceManager.GetString("NASA_PAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGDF.
        /// </summary>
        internal static string NASA_PGDF {
            get {
                return ResourceManager.GetString("NASA_PGDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMA.
        /// </summary>
        internal static string NASA_PMA {
            get {
                return ResourceManager.GetString("NASA_PMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMA 2.
        /// </summary>
        internal static string NASA_PMA_2 {
            get {
                return ResourceManager.GetString("NASA_PMA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRE-BREATHE.
        /// </summary>
        internal static string NASA_PRE_BREATHE {
            get {
                return ResourceManager.GetString("NASA_PRE_BREATHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREBREATHE.
        /// </summary>
        internal static string NASA_PREBREATHE {
            get {
                return ResourceManager.GetString("NASA_PREBREATHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print_Area.
        /// </summary>
        internal static string NASA_PRINT_AREA {
            get {
                return ResourceManager.GetString("NASA_PRINT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        internal static string NASA_QUEST {
            get {
                return ResourceManager.GetString("NASA_QUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCC.
        /// </summary>
        internal static string NASA_RCC {
            get {
                return ResourceManager.GetString("NASA_RCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS.
        /// </summary>
        internal static string NASA_RCS {
            get {
                return ResourceManager.GetString("NASA_RCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS.
        /// </summary>
        internal static string NASA_RMS {
            get {
                return ResourceManager.GetString("NASA_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPCM.
        /// </summary>
        internal static string NASA_RPCM {
            get {
                return ResourceManager.GetString("NASA_RPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        internal static string NASA_RPM {
            get {
                return ResourceManager.GetString("NASA_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1.
        /// </summary>
        internal static string NASA_S1 {
            get {
                return ResourceManager.GetString("NASA_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S2.
        /// </summary>
        internal static string NASA_S2 {
            get {
                return ResourceManager.GetString("NASA_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3.
        /// </summary>
        internal static string NASA_S3 {
            get {
                return ResourceManager.GetString("NASA_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S4.
        /// </summary>
        internal static string NASA_S4 {
            get {
                return ResourceManager.GetString("NASA_S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S5.
        /// </summary>
        internal static string NASA_S5 {
            get {
                return ResourceManager.GetString("NASA_S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S6.
        /// </summary>
        internal static string NASA_S6 {
            get {
                return ResourceManager.GetString("NASA_S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SASA.
        /// </summary>
        internal static string NASA_SASA {
            get {
                return ResourceManager.GetString("NASA_SASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITE.
        /// </summary>
        internal static string NASA_SITE {
            get {
                return ResourceManager.GetString("NASA_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSPTS.
        /// </summary>
        internal static string NASA_SSPTS {
            get {
                return ResourceManager.GetString("NASA_SSPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRMS.
        /// </summary>
        internal static string NASA_SSRMS {
            get {
                return ResourceManager.GetString("NASA_SSRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STS.
        /// </summary>
        internal static string NASA_STS {
            get {
                return ResourceManager.GetString("NASA_STS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATLANTIS.
        /// </summary>
        internal static string NASA_STS_ATLANTIS {
            get {
                return ResourceManager.GetString("NASA_STS_ATLANTIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOVERY.
        /// </summary>
        internal static string NASA_STS_DISCOVERY {
            get {
                return ResourceManager.GetString("NASA_STS_DISCOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDEAVOR.
        /// </summary>
        internal static string NASA_STS_ENDEAVOR {
            get {
                return ResourceManager.GetString("NASA_STS_ENDEAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBJECT.
        /// </summary>
        internal static string NASA_SUBJECT {
            get {
                return ResourceManager.GetString("NASA_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-RAD.
        /// </summary>
        internal static string NASA_T_RAD {
            get {
                return ResourceManager.GetString("NASA_T_RAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDRE.
        /// </summary>
        internal static string NASA_TDRE {
            get {
                return ResourceManager.GetString("NASA_TDRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDRW.
        /// </summary>
        internal static string NASA_TDRW {
            get {
                return ResourceManager.GetString("NASA_TDRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDRZ.
        /// </summary>
        internal static string NASA_TDRZ {
            get {
                return ResourceManager.GetString("NASA_TDRZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TI.
        /// </summary>
        internal static string NASA_TI {
            get {
                return ResourceManager.GetString("NASA_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPS.
        /// </summary>
        internal static string NASA_TPS {
            get {
                return ResourceManager.GetString("NASA_TPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  UNDOCKING.
        /// </summary>
        internal static string NASA_UNDOCKING {
            get {
                return ResourceManager.GetString("NASA_UNDOCKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITY.
        /// </summary>
        internal static string NASA_UNITY {
            get {
                return ResourceManager.GetString("NASA_UNITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTR.
        /// </summary>
        internal static string NASA_VTR {
            get {
                return ResourceManager.GetString("NASA_VTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTR PLAYBACK.
        /// </summary>
        internal static string NASA_VTR_PLAYBACK {
            get {
                return ResourceManager.GetString("NASA_VTR_PLAYBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WLE.
        /// </summary>
        internal static string NASA_WLE {
            get {
                return ResourceManager.GetString("NASA_WLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z1.
        /// </summary>
        internal static string NASA_Z1 {
            get {
                return ResourceManager.GetString("NASA_Z1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;DayOfWeek&gt;SUNDAY|MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY),\s+(?&lt;Month&gt;JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER)\s+(?&lt;Day&gt;\d+).
        /// </summary>
        internal static string RG_DATE_HEADER {
            get {
                return ResourceManager.GetString("RG_DATE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Eva&gt;EVA)\s+(?&lt;Number&gt;#\d+)\s+(?&lt;Activity&gt;BEGINS|ENDS).
        /// </summary>
        internal static string RG_EVA_ACTIVITY {
            get {
                return ResourceManager.GetString("RG_EVA_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;FlightDay&gt;FD)\s+(?&lt;Day&gt;\d+).
        /// </summary>
        internal static string RG_FLIGHDAY_HEADER {
            get {
                return ResourceManager.GetString("RG_FLIGHDAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Shuttle&gt;ATLANTIS|DISCOVERY|ENDEAVOR)?(?:\s*/?\s*)?(?&lt;ISS&gt;ISS)(?:\s*)(?&lt;Activity&gt;CREW SLEEP BEGINS|CREW WAKE UP).
        /// </summary>
        internal static string RG_ISS_CREW_SLEEP_ACTIVITY {
            get {
                return ResourceManager.GetString("RG_ISS_CREW_SLEEP_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Month&gt;[01][0-9])/(?&lt;Day&gt;[0-3][0-9])/(?&lt;Year&gt;[0-9][0-9]).
        /// </summary>
        internal static string RG_MM_DD_YY {
            get {
                return ResourceManager.GetString("RG_MM_DD_YY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Shuttle&gt;ATLANTIS|DISCOVERY|ENDEAVOR)(?:\s*/?\s*)?(?&lt;ISS&gt;ISS)?(?:\s*)(?&lt;Activity&gt;CREW SLEEP BEGINS|CREW WAKE UP).
        /// </summary>
        internal static string RG_SHUTTLE_CREW_SLEEP_ACTIVITY {
            get {
                return ResourceManager.GetString("RG_SHUTTLE_CREW_SLEEP_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Double.
        /// </summary>
        internal static string SYSTEM_DOUBLE {
            get {
                return ResourceManager.GetString("SYSTEM_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String.
        /// </summary>
        internal static string SYSTEM_STRING {
            get {
                return ResourceManager.GetString("SYSTEM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIEFING.
        /// </summary>
        internal static string TM_BRIEFING {
            get {
                return ResourceManager.GetString("TM_BRIEFING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE OF COMMAND CEREMONY.
        /// </summary>
        internal static string TM_CHANGE_COMMAND_CEREMONY {
            get {
                return ResourceManager.GetString("TM_CHANGE_COMMAND_CEREMONY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTDOWN STATUS BRIEFING.
        /// </summary>
        internal static string TM_COUNTDOWN_STATUS_BRIEFING {
            get {
                return ResourceManager.GetString("TM_COUNTDOWN_STATUS_BRIEFING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREW SLEEP BEGINS.
        /// </summary>
        internal static string TM_CREW_SLEEP_BEGINS {
            get {
                return ResourceManager.GetString("TM_CREW_SLEEP_BEGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREW_WAKE_UP.
        /// </summary>
        internal static string TM_CREW_WAKE_UP {
            get {
                return ResourceManager.GetString("TM_CREW_WAKE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEORBIT BURN.
        /// </summary>
        internal static string TM_DEORBIT_BURN {
            get {
                return ResourceManager.GetString("TM_DEORBIT_BURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVIEW.
        /// </summary>
        internal static string TM_INTERVIEW {
            get {
                return ResourceManager.GetString("TM_INTERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLIGHT DIRECTOR UPDATE.
        /// </summary>
        internal static string TM_ISS_FLIGHT_DIRECTOR_UPDATE {
            get {
                return ResourceManager.GetString("TM_ISS_FLIGHT_DIRECTOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION STATUS BRIEFING.
        /// </summary>
        internal static string TM_MISSION_STATUS_BRIEFING {
            get {
                return ResourceManager.GetString("TM_MISSION_STATUS_BRIEFING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS CONFERENCE.
        /// </summary>
        internal static string TM_NEWS_CONFERENCE {
            get {
                return ResourceManager.GetString("TM_NEWS_CONFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAO EVENT.
        /// </summary>
        internal static string TM_PAO_EVENT {
            get {
                return ResourceManager.GetString("TM_PAO_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST-MMT BRIEFING.
        /// </summary>
        internal static string TM_POST_MMT_BRIEFING {
            get {
                return ResourceManager.GetString("TM_POST_MMT_BRIEFING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;FlightDay&gt;FLIGHT DAY)\s+(?&lt;Day&gt;\d+)\s+(?&lt;Highlights&gt;HIGHLIGHTS).
        /// </summary>
        internal static string TM_RG_FLIGHT_DAY_HIGHLIGHTS {
            get {
                return ResourceManager.GetString("TM_RG_FLIGHT_DAY_HIGHLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO FILE.
        /// </summary>
        internal static string TM_VIDEO_FILE {
            get {
                return ResourceManager.GetString("TM_VIDEO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-09:00) Alaska.
        /// </summary>
        internal static string TZ_ALASKAN {
            get {
                return ResourceManager.GetString("TZ_ALASKAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Central Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_CENTRAL {
            get {
                return ResourceManager.GetString("TZ_CENTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_DEFAULT {
            get {
                return ResourceManager.GetString("TZ_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_EASTERN {
            get {
                return ResourceManager.GetString("TZ_EASTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-10:00) Hawaii.
        /// </summary>
        internal static string TZ_HAWAIIAN {
            get {
                return ResourceManager.GetString("TZ_HAWAIIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Central Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_JOHNSON_SPACE_CENTER {
            get {
                return ResourceManager.GetString("TZ_JOHNSON_SPACE_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-07:00) Mountain Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_MOUNTAIN {
            get {
                return ResourceManager.GetString("TZ_MOUNTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-08:00) Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_PACIFIC {
            get {
                return ResourceManager.GetString("TZ_PACIFIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string TZ_US_EASTERN {
            get {
                return ResourceManager.GetString("TZ_US_EASTERN", resourceCulture);
            }
        }
    }
}
