//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermanentVacations.Nasa.Sts.OutlookCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PermanentVacations.Nasa.Sts.OutlookCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Exception.
        /// </summary>
        internal static string ERR_COM_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_COM_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERR_MESSAGE_BOX_HDR_ERROR {
            get {
                return ResourceManager.GetString("ERR_MESSAGE_BOX_HDR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no NASA STS TV Schedule loaded to transfer to Outlook.
        /// </summary>
        internal static string ERR_NO_EXCEL_SCHEDULE {
            get {
                return ResourceManager.GetString("ERR_NO_EXCEL_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Categories] =.
        /// </summary>
        internal static string FILTER_CATEGORIES {
            get {
                return ResourceManager.GetString("FILTER_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([Start] &gt;= &apos;{0}&apos; AND [End] &lt;= &apos;{1}&apos;).
        /// </summary>
        internal static string FMT_DATE_FILTER {
            get {
                return ResourceManager.GetString("FMT_DATE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([Start] = &apos;{0}&apos;) AND ([End] = &apos;{1}&apos;) AND ([Subject] = &apos;{2}&apos;) AND ([Location] = &apos;{3}&apos;).
        /// </summary>
        internal static string FMT_FILTER_DATE_SUBJECT_LOCATION {
            get {
                return ResourceManager.GetString("FMT_FILTER_DATE_SUBJECT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading NASA Schedule File: .
        /// </summary>
        internal static string ID_BULKIMPORT_READFILE {
            get {
                return ResourceManager.GetString("ID_BULKIMPORT_READFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing selected Calendar entries from Outlook.
        /// </summary>
        internal static string ID_BULKIMPORT_REMOVINGOUTLOOKENTRIES {
            get {
                return ResourceManager.GetString("ID_BULKIMPORT_REMOVINGOUTLOOKENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting all NASA Schedule Entries.
        /// </summary>
        internal static string ID_BULKIMPORT_SELECTALLEXCEL {
            get {
                return ResourceManager.GetString("ID_BULKIMPORT_SELECTALLEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Calendar Items to delete.
        /// </summary>
        internal static string ID_BULKIMPORT_SMARTSELECT {
            get {
                return ResourceManager.GetString("ID_BULKIMPORT_SMARTSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring to Outlook.
        /// </summary>
        internal static string ID_BULKIMPORT_TRANSFERTOOUTLOOK {
            get {
                return ResourceManager.GetString("ID_BULKIMPORT_TRANSFERTOOUTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string ID_BUSY {
            get {
                return ResourceManager.GetString("ID_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy reading NASA STS TV Schedule.
        /// </summary>
        internal static string ID_BUSY_READING_EXCEL {
            get {
                return ResourceManager.GetString("ID_BUSY_READING_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy deleting appointments from Outlook.
        /// </summary>
        internal static string ID_BUSY_REMOVING_APPOINTMENTS {
            get {
                return ResourceManager.GetString("ID_BUSY_REMOVING_APPOINTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy transferring NASA STS TV Schedule to Outlook.
        /// </summary>
        internal static string ID_BUSY_TRANSFERRING_SCHEDULE {
            get {
                return ResourceManager.GetString("ID_BUSY_TRANSFERRING_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASA TV Schedule - STS.
        /// </summary>
        internal static string ID_DEFALT_CATEGORY {
            get {
                return ResourceManager.GetString("ID_DEFALT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\Documents and Settings\RalphHightower\My Documents\Nasa\.
        /// </summary>
        internal static string ID_DEFAULT_DIRECTORY {
            get {
                return ResourceManager.GetString("ID_DEFAULT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open multiple NASA STS TV Schedules.
        /// </summary>
        internal static string ID_OPEN_MULTIPLE_EXCEL_FILES {
            get {
                return ResourceManager.GetString("ID_OPEN_MULTIPLE_EXCEL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open single NASA STS TV Schedule.
        /// </summary>
        internal static string ID_OPEN_SINGLE_EXCEL_FILE {
            get {
                return ResourceManager.GetString("ID_OPEN_SINGLE_EXCEL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASA Space Shuttle TV Schedule Transfer to Outlook Calendar.
        /// </summary>
        internal static string ID_PROGRAMTITLE {
            get {
                return ResourceManager.GetString("ID_PROGRAMTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ID_READY {
            get {
                return ResourceManager.GetString("ID_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take a long while....
        /// </summary>
        internal static string ID_THIS_WILL_TAKE_A_LONG_WHILE {
            get {
                return ResourceManager.GetString("ID_THIS_WILL_TAKE_A_LONG_WHILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string ID_TZ_DEFAULT {
            get {
                return ResourceManager.GetString("ID_TZ_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time = .
        /// </summary>
        internal static string INFO_ELAPSED_TIME {
            get {
                return ResourceManager.GetString("INFO_ELAPSED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFO_INFORMATION {
            get {
                return ResourceManager.GetString("INFO_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads and imports multiple NASA TV Schedules into Outlook.
        /// </summary>
        internal static string MOUSEHOVER_BULKIMPORT {
            get {
                return ResourceManager.GetString("MOUSEHOVER_BULKIMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if Space Shuttle is docked to Space Station.
        /// </summary>
        internal static string MOUSEHOVER_DOCKED {
            get {
                return ResourceManager.GetString("MOUSEHOVER_DOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule entries from the NASA STS TV Schedule.
        /// </summary>
        internal static string MOUSEHOVER_EXCELDATAGRID {
            get {
                return ResourceManager.GetString("MOUSEHOVER_EXCELDATAGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quits the application.
        /// </summary>
        internal static string MOUSEHOVER_EXITAPPLICATION {
            get {
                return ResourceManager.GetString("MOUSEHOVER_EXITAPPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} week window of Outlook Calendar Appointments.
        /// </summary>
        internal static string MOUSEHOVER_MISSIONDATE {
            get {
                return ResourceManager.GetString("MOUSEHOVER_MISSIONDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a NASA STS TV schedule and read the schedule entries.
        /// </summary>
        internal static string MOUSEHOVER_OPENNASATVSCHEDULE {
            get {
                return ResourceManager.GetString("MOUSEHOVER_OPENNASATVSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if Space Shuttle is in orbit.
        /// </summary>
        internal static string MOUSEHOVER_ORBIT {
            get {
                return ResourceManager.GetString("MOUSEHOVER_ORBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Categories to restrict Outlook Calendar Appointments to.
        /// </summary>
        internal static string MOUSEHOVER_OUTLOOKCATEGORIES {
            get {
                return ResourceManager.GetString("MOUSEHOVER_OUTLOOKCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Calendar Appointment items in schedule.
        /// </summary>
        internal static string MOUSEHOVER_OUTLOOKDATAGRID {
            get {
                return ResourceManager.GetString("MOUSEHOVER_OUTLOOKDATAGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the Outlook Categories.
        /// </summary>
        internal static string MOUSEHOVER_REFRESHCATEGORIES {
            get {
                return ResourceManager.GetString("MOUSEHOVER_REFRESHCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes selected Appointment Items from the Outlook Calendar.
        /// </summary>
        internal static string MOUSEHOVER_REMOVESELECTEDITEMS {
            get {
                return ResourceManager.GetString("MOUSEHOVER_REMOVESELECTEDITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all schedule entries in the Excel schedule.
        /// </summary>
        internal static string MOUSEHOVER_SELECTALLEXCEL {
            get {
                return ResourceManager.GetString("MOUSEHOVER_SELECTALLEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all Outlook Appointment Items.
        /// </summary>
        internal static string MOUSEHOVER_SELECTALLOUTLOOK {
            get {
                return ResourceManager.GetString("MOUSEHOVER_SELECTALLOUTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects Appointment Items in Outlook that are in the date and time range of the Excel schedule.
        /// </summary>
        internal static string MOUSEHOVER_SMARTSELECT {
            get {
                return ResourceManager.GetString("MOUSEHOVER_SMARTSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers selected items from NASA TV Schedule to Outlook.
        /// </summary>
        internal static string MOUSEHOVER_TRANSFERTVSCHEDULE {
            get {
                return ResourceManager.GetString("MOUSEHOVER_TRANSFERTVSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all schedule entries in the Excel schedule.
        /// </summary>
        internal static string MOUSEHOVER_UNSELECTALLEXCEL {
            get {
                return ResourceManager.GetString("MOUSEHOVER_UNSELECTALLEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselects all Outlook Appointment Items.
        /// </summary>
        internal static string MOUSEHOVER_UNSELECTALLOUTLOOK {
            get {
                return ResourceManager.GetString("MOUSEHOVER_UNSELECTALLOUTLOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone for the Outlook Appointment Items to be converted to.
        /// </summary>
        internal static string MOUSEHOVER_VIEWINGTIMEZONE {
            get {
                return ResourceManager.GetString("MOUSEHOVER_VIEWINGTIMEZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OR .
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI.
        /// </summary>
        internal static string OUTLOOK_MAPI {
            get {
                return ResourceManager.GetString("OUTLOOK_MAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Start].
        /// </summary>
        internal static string OUTLOOK_START {
            get {
                return ResourceManager.GetString("OUTLOOK_START", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SpaceShuttle_32X32_256 {
            get {
                object obj = ResourceManager.GetObject("SpaceShuttle_32X32-256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time doing Bulk Import = .
        /// </summary>
        internal static string TIMER_ELAPSED_TIME_BULK_IMPORT {
            get {
                return ResourceManager.GetString("TIMER_ELAPSED_TIME_BULK_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time Reading NASA STS TV Schedule = .
        /// </summary>
        internal static string TIMER_ELAPSED_TIME_READING_EXCEL {
            get {
                return ResourceManager.GetString("TIMER_ELAPSED_TIME_READING_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time Removing Schedule from Outlook = .
        /// </summary>
        internal static string TIMER_ELAPSED_TIME_REMOVING_SCHEDULE {
            get {
                return ResourceManager.GetString("TIMER_ELAPSED_TIME_REMOVING_SCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time Transferring Schedule to Outlook = .
        /// </summary>
        internal static string TIMER_ELAPSED_TIME_TRANFERRING {
            get {
                return ResourceManager.GetString("TIMER_ELAPSED_TIME_TRANFERRING", resourceCulture);
            }
        }
    }
}
